import { Document, Page, Text, View, Image, StyleSheet, PDFDownloadLink } from '@react-pdf/renderer';
import { renderToBuffer } from '@react-pdf/renderer';

// Define styles
const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica' },
  title: { fontSize: 24, fontWeight: 'bold', marginBottom: 20, textAlign: 'center' },
  section: { marginBottom: 15 },
  label: { fontSize: 12, fontWeight: 'bold', marginBottom: 5 },
  value: { fontSize: 12, marginBottom: 10 },
  image: { width: '100%', maxHeight: 300, marginBottom: 20 },
  row: { flexDirection: 'row', marginBottom: 5 },
  col: { flex: 1 },
  score: { fontSize: 14, fontWeight: 'bold' },
  defect: { fontSize: 12, color: 'red', marginBottom: 2 },
  suggestion: { fontSize: 12, color: 'blue', marginBottom: 2 },
});

interface ReportData {
  imageUrl: string;
  fabricType: string;
  weavePattern: string;
  warpCount: number;
  weftCount: number;
  threadDensity: number;
  qualityScore: number;
  confidenceScore: number;
  defects: string[];
  suggestions: string[];
  analysisId: string;
  userName: string;
}

// PDF Document component
const ReportDocument = (data: ReportData) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <Text style={styles.title}>ThreadCounty Fabric Analysis Report</Text>
      {/* eslint-disable-next-line jsx-a11y/alt-text */}
      <Image src={data.imageUrl} style={styles.image} />
      <View style={styles.section}>
        <Text style={styles.label}>Fabric Type: {data.fabricType}</Text>
        <Text style={styles.label}>Weave Pattern: {data.weavePattern}</Text>
        <Text style={styles.label}>Warp Count: {data.warpCount} threads/inch</Text>
        <Text style={styles.label}>Weft Count: {data.weftCount} threads/inch</Text>
        <Text style={styles.label}>Thread Density: {data.threadDensity} threads/inch</Text>
      </View>
      <View style={styles.section}>
        <Text style={styles.label}>Quality Score: <Text style={styles.score}>{data.qualityScore}/100</Text></Text>
        <Text style={styles.label}>Confidence Score: <Text style={styles.score}>{data.confidenceScore}%</Text></Text>
      </View>
      {data.defects.length > 0 && (
        <View style={styles.section}>
          <Text style={styles.label}>Defects Detected:</Text>
          {data.defects.map((defect, i) => (
            <Text key={i} style={styles.defect}>• {defect}</Text>
          ))}
        </View>
      )}
      {data.suggestions.length > 0 && (
        <View style={styles.section}>
          <Text style={styles.label}>AI Suggestions:</Text>
          {data.suggestions.map((suggestion, i) => (
            <Text key={i} style={styles.suggestion}>• {suggestion}</Text>
          ))}
        </View>
      )}
      <Text style={{ fontSize: 10, marginTop: 30, color: 'gray' }}>
        Report generated by ThreadCounty AI | Analysis ID: {data.analysisId}
      </Text>
    </Page>
  </Document>
);

export async function generatePDFReport(data: ReportData): Promise<Buffer> {
  const doc = ReportDocument(data);
  const buffer = await renderToBuffer(doc);
  return buffer;
}